import * as React from 'react';
import { ChatBubbleProps, ChatBubbleStyles, MessageRenderProps } from '../ChatBubble';
import { BubbleGroupStyles } from './styles';
import { Message } from '../';
import { Author } from '../Author';
import { AvatarProps, AvatarClasses } from '../Avatar';
import { LastSeenAvatarProps, LastSeenAvatarStyles, LastSeenAvatarClasses } from '../LastSeenAvatar';
import { AvatarStyles } from './../Avatar';
import { ChatBubbleClasses } from './../ChatBubble';
import { BubbleGroupClasses } from './classes';
export * from './styles';
export * from './classes';
export interface BubbleGroupProps<T = string> {
    yourAuthorId?: number;
    messages: Message<T>[];
    author: Author;
    authors?: Author[];
    showRecipientAvatar?: boolean;
    bubblesCentered?: boolean;
    classes?: BubbleGroupClasses;
    chatBubbleClasses?: ChatBubbleClasses;
    avatarClasses?: AvatarClasses;
    lastSeenAvatarClasses?: LastSeenAvatarClasses;
    styles?: BubbleGroupStyles;
    chatBubbleStyles?: ChatBubbleStyles;
    avatarStyles?: AvatarStyles;
    lastSeenAvatarStyles?: LastSeenAvatarStyles;
    CustomAvatar?: (props: AvatarProps) => JSX.Element;
    CustomMessageRender?: (props: MessageRenderProps<T>) => JSX.Element | string;
    CustomLastSeenAvatar?: (props: LastSeenAvatarProps) => JSX.Element;
    CustomChatBubble?: (props: ChatBubbleProps<T>) => JSX.Element;
    CustomSystemChatBubble?: (props: ChatBubbleProps<T>) => JSX.Element;
    showRecipientLastSeenMessage?: boolean;
}
declare function BubbleGroup<T = string>(props: BubbleGroupProps<T>): JSX.Element;
declare const Memoized: React.MemoExoticComponent<typeof BubbleGroup>;
export default Memoized;
export { Memoized as BubbleGroup };
